"""Pydantic schemas for API request/response validation."""

from pydantic import BaseModel, Field, model_validator


class LoanApplication(BaseModel):
    """Applicant financial data submitted for underwriting.

    All fields match the features the XGBoost model was trained on.
    """

    limit_bal: float = Field(
        ..., description="Total credit limit", example=200000
    )
    age: int = Field(
        ..., ge=18, le=120, description="Applicant age in years", example=35
    )
    pay_0: int = Field(
        ...,
        ge=-2,
        le=8,
        description=(
            "Repayment status last month. "
            "-2 = no consumption that month, "
            "-1 = pay duly, 0 = no delay, 1+ = months delayed"
        ),
        example=-1,
    )
    pay_2: int = Field(
        ...,
        ge=-2,
        le=8,
        description=(
            "Repayment status 2 months ago (same scale as pay_0: "
            "-2 = no consumption, -1 = pay duly, 0 = no delay, 1+ = delayed)"
        ),
        example=-1,
    )
    pay_3: int = Field(
        ...,
        ge=-2,
        le=8,
        description=(
            "Repayment status 3 months ago (same scale as pay_0: "
            "-2 = no consumption, -1 = pay duly, 0 = no delay, 1+ = delayed)"
        ),
        example=-1,
    )
    pay_amt1: float = Field(
        ...,
        ge=0,
        description="Amount paid last month",
        example=5000,
    )
    bill_amt1: float = Field(
        ...,
        ge=0,
        description="Bill statement amount last month",
        example=30000,
    )

    @model_validator(mode="after")
    def check_credit_limits(self):
        errs = []
        if self.bill_amt1 > self.limit_bal:
            errs.append(f"bill_amt1 ({self.bill_amt1}) exceeds credit limit ({self.limit_bal})")
        if self.pay_amt1 > self.bill_amt1:
            errs.append(f"pay_amt1 ({self.pay_amt1}) exceeds bill amount ({self.bill_amt1})")
        if errs:
            raise ValueError("; ".join(errs))
        return self


class FeatureContribution(BaseModel):
    """SHAP explanation for a single feature.

    Shows how much a specific feature value pushed the prediction
    above or below the baseline (average default probability).
    """

    feature_name: str = Field(
        ..., description="Feature name (e.g. PAY_0, LIMIT_BAL)", example="PAY_0"
    )
    feature_value: float = Field(
        ..., description="The actual value the applicant provided", example=-1
    )
    shap_value: float = Field(
        ...,
        description=(
            "How much this feature pushed the prediction. "
            "Positive = increased default risk, Negative = decreased risk."
        ),
        example=0.15,
    )
    impact: str = Field(
        ...,
        description="Direction of impact: increases_risk or decreases_risk",
        example="decreases_risk",
    )


class RiskAssessment(BaseModel):
    """Output of the ML model prediction."""

    risk: str = Field(
        ..., description="Risk category: Low or High", example="Low"
    )
    default_probability: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Predicted probability of default (0-1)",
        example=0.32,
    )
    features_used: list[str] = Field(
        ..., description="Feature names used by the model"
    )
    shap_explanations: list[FeatureContribution] = Field(
        ..., description="Per-feature SHAP contributions explaining the prediction"
    )
    risk_report: str = Field(
        "",
        description=(
            "Narrative risk assessment report generated by an LLM. "
            "Only present if an LLM provider is configured."
        ),
    )


class ErrorResponse(BaseModel):
    """Standard error response."""

    detail: str = Field(..., description="Error message")
